In [1]:
from numpy import array, sqrt, sin, cos, arctan, pi, set_printoptions
from numpy.linalg import norm
from geodesy import dms2rad, geod2ECEF, rad2deg

set_printoptions(precision=1, suppress=True)

# Jordradius
R = 6371e3     # meter

# Geodeetiske koordinater FLOY
lat1 = dms2rad(59, 39, 56.51989)  # radianer
lon1 = dms2rad(10, 46, 40.14889)  # radianer
h1 = 142.730                      # meter

# Beregner ECEF koordinater FLOY
X1, Y1, Z1 = geod2ECEF(R, R, lat1, lon1, h1)

FLOY = array([[X1],
              [Y1],
              [Z1]])
print(FLOY, norm(FLOY))

[[3160948.7]
 [ 601715.1]
 [5498891. ]] 6371142.7299999995


In [2]:
# Geodeetiske koordinater SSIR
lat2 = dms2rad(59, 39, 58.14943)  # radianer
lon2 = dms2rad(10, 46, 37.91682)  # radianer
h2 = 136.039                      # meter

# Beregner ECEF koordinater SSIR
X2, Y2, Z2 = geod2ECEF(R, R, lat2, lon2, h2)

SSIR = array([[X2],
              [Y2],
              [Z2]])
print(SSIR, norm(SSIR))

[[3160909.2]
 [ 601672.1]
 [5498910.6]] 6371136.039


In [3]:
# Baselinje mellom FLOY og SSIR
dX = SSIR - FLOY
print(dX)
print(f"Lengde = {norm(dX):5.1f} m")

[[-39.5]
 [-43. ]
 [ 19.6]]
Lengde =  61.6 m


In [4]:
# Transformasjon til toposentrisk system (e, n ,u)
Ce_g = array([[-sin(lon1), cos(lon1), 0],
              [-sin(lat1)*cos(lon1), -sin(lat1)*sin(lon1), cos(lat1)],
              [cos(lat1)*cos(lon1), cos(lat1)*sin(lon1), sin(lat1)]])

dX_enu = Ce_g@dX
print(dX_enu)
print(f"Lengde = {norm(dX):5.1f} m")

[[-34.8]
 [ 50.3]
 [ -6.7]]
Lengde =  61.6 m


In [5]:
# Beregner vinkel og avstand mellom FLOY og SSIR
alpha = arctan(dX_enu[0, 0]/dX_enu[1, 0])

# Beregner asimut (heading)
heading = rad2deg(alpha + 2*pi)

print(f"Asimut  = {heading:5.1f} grader")
print(f"Avstand = {norm(dX_enu):5.1f} m")

Asimut  = 325.3 grader
Avstand =  61.6 m
