In [1]:
# Import
from numpy import array, mean
from numpy.linalg import inv

# Punkt A (KIRKE)

# EUREF89
NA = 6616156.845   # meter
EA = 599609.151    # meter

# NGO1948
xA = 186085.461    # meter
yA = 2836.307      # meter


# Punkt B (FLOY)

# EUREF89
NB = 6615523.164   # meter
EB = 600153.486    # meter

# NGO1948
xB = 185437.725    # meter
yB = 3364.166      # meter


# Punkt C (GPS1)

# EUREF89
NC = 6614931.501   # meter
EC = 600389.145    # meter

# NGO1948
xC = 184839.971    # meter
yC = 3584.454      # meter

In [2]:
# Beregner transformasjonsparametre (P2 = T + P1)
P1 = array([[xA],
            [yA]])

P2 = array([[NA],
            [EA]])

# Translasjon bestemt fra punkt A
TA = P2 - P1
print(TA)

P1 = array([[xB],
            [yB]])

P2 = array([[NB],
            [EB]])

# Translasjon bestemt fra punkt B
TB = P2 - P1
print(TB)

# Gjennomsnittlig translasjon
T = mean([TA, TB], axis=0)
print(T)

[[6430071.384]
 [ 596772.844]]
[[6430085.439]
 [ 596789.32 ]]
[[6430078.4115]
 [ 596781.082 ]]


In [3]:
# Transformerer ukjent punkt
P1 = array([[xC],
            [yC]])

# Transformasjon (kun translasjon)
P2 = T + P1
print(P2)

# Kjente koordinater
P2kjent = array([[NC],
                 [EC]])

# Avvik fra kjente koordinater
print(P2kjent - P2)

[[6614918.3825]
 [ 600365.536 ]]
[[13.1185]
 [23.609 ]]


In [4]:
# Beregner transformasjonsparametre (P2 = T + m@R@P1)

y = array([[NA],
           [EA],
           [NB],
           [EB]])

A = array([[1, 0, xA, yA],
           [0, 1, yA, -xA],
           [1, 0, xB, yB],
           [0, 1, yB, -xB]])

x = inv(A)@y
tx, ty, a, b = x.flatten()
print(f"tx = {tx:12.3f}m")
print(f"ty = {ty:12.3f}m")
print(f"a = {a:12.5f}")
print(f"b = {b:12.5f}")

tx =  6430106.346m
ty =   601596.204m
a =      0.99942
b =      0.02591


In [5]:
# Transformerer ukjent punkt
P1 = array([[xC],
            [yC]])

T = array([[tx],
           [ty]])

mR = array([[a, b],
            [-b, a]])

# Transformasjon (Helmert)
P2 = T + mR@P1
print(P2)

# Kjente koordinater
P2kjent = array([[NC],
                 [EC]])

# Avvik fra kjente koordinater
print(P2kjent - P2)

[[6614931.46632098]
 [ 600389.13416341]]
[[0.03467902]
 [0.01083659]]
