In [1]:
from numpy import array, sin, cos, set_printoptions
from geodesy import deg2rad

set_printoptions(precision=1, suppress=True)

alpha = deg2rad(30)   # radianer

R = array([[cos(alpha), sin(alpha)],
           [-sin(alpha), cos(alpha)]])

P11 = array([[1],
             [1]])

P12 = array([[1],
             [2]])

# Rotasjon (Rotere om origo)
P21 = R@P11
print(P21)

[[1.4]
 [0.4]]


In [2]:
P22 = R@P12
print(P22)

[[1.9]
 [1.2]]


In [3]:
# Rotasjon og translasjon (rotere om P11)
T = array([[1],
           [1]])

P21 = R@(P11 - T) + T
print(P21)

[[1.]
 [1.]]


In [4]:
P22 = R@(P12 - T) + T
print(P22)

[[1.5]
 [1.9]]
