In [1]:
from numpy import array, sin, cos
from geodesy import deg2rad

# Punkt
P1 = array([[1],
            [2]])

# Translasjon
T = array([[3],
           [-1]])
P2 = T + P1
print(P2)

[[4]
 [1]]


In [2]:
# Skalering
S = array([[2, 0],
           [0, 1]])
P2 = S@P1
print(P2)

[[2]
 [2]]


In [3]:
# Rotasjon
alpha = deg2rad(30)

R = array([[cos(alpha), sin(alpha)],
           [-sin(alpha), cos(alpha)]])
P2 = R@P1
print(P2)

[[1.8660254 ]
 [1.23205081]]


In [4]:
# Eksempel
A = array([[1, 2],
           [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [5]:
B = array([[5, 6],
           [7, 8]])
print(B)

[[5 6]
 [7 8]]


In [6]:
# Matrisemultiplikasjon
print(A@B)

[[19 22]
 [43 50]]


In [7]:
# Elementvis multiplikasjon
print(A*B)

[[ 5 12]
 [21 32]]
