In [1]:
from numpy import array, sin, cos, set_printoptions
from geodesy import deg2rad

set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

P1 = array([[1],
            [2]])

# Translation
T = array([[2],
           [3]])

# Scale
S = array([[0.5, 0],
           [0, 2]])

# Rotation
alpha = deg2rad(30)
R = array([[cos(alpha), sin(alpha)],
           [-sin(alpha), cos(alpha)]])

In [2]:
# Translation
P2 = T + P1
print(P2)

[[3]
 [5]]


In [3]:
# Scale
P2 = S@P1
print(P2)

[[0.500]
 [4.000]]


In [4]:
# Rotation
P2 = R@P1
print(P2)

[[1.866]
 [1.232]]


In [5]:
# Combined transformation
P2 = R@S@(T + P1)
print(P2)

[[6.299]
 [7.910]]
