In [1]:
from numpy import array

A = array([[1, 2],
           [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [2]:
B = array([[5, 6],
           [7, 8]])
print(B)

[[5 6]
 [7 8]]


In [3]:
# Matrix multiplication
print(A@B)

[[19 22]
 [43 50]]


In [4]:
# Elementwise multiplication
print(A*B)

[[ 5 12]
 [21 32]]
