In [1]:
from numpy import array, sin, cos
from geodesy import deg2rad

def Rx(alpha):
    return array([[1 ,0 , 0],
                  [0, cos(alpha), -sin(alpha)],
                  [0, sin(alpha), cos(alpha)]])

def Ry(beta):
    return array([[cos(beta) ,0 , sin(beta)],
                  [0, 1, 0],
                  [-sin(beta), 0, cos(beta)]])

def Rz(gamma):
    return array([[cos(gamma) ,-sin(gamma) , 0],
                  [sin(gamma), cos(gamma), 0],
                  [0, 0, 1]])


alpha = deg2rad(30)
beta = deg2rad(40)
gamma = deg2rad(50)

R = Rz(gamma)@Ry(beta)@Rx(alpha)
print(R)

[[ 0.49240388 -0.45682599  0.74084306]
 [ 0.58682409  0.80287234  0.10504046]
 [-0.64278761  0.38302222  0.66341395]]


In [2]:
from numpy import array, sqrt
from geodesy import dms2rad, geod2ECEF, ECEF2enu, rad2grad, arctanc

# WGS84
a = 6378137
f = 1/298.257223563
b = a*(1 - f)

# SSIR
lats = dms2rad([59, 39, 58.14943])
lons = dms2rad([10, 46, 37.91682])
hs = 136.039

[Xs, Ys, Zs] = geod2ECEF(a, b, lats, lons, hs)
SSIR = array([[Xs],
              [Ys],
              [Zs]])


# ROSA
latr = dms2rad([59, 39, 57.93089])
lonr = dms2rad([10, 46, 30.22916])
hr = 137.467

[Xr, Yr, Zr] = geod2ECEF(a, b, latr, lonr, hr)
ROSA = array([[Xr],
              [Yr],
              [Zr]])

dP = ROSA - SSIR

dX = dP[0, 0]
dY = dP[1, 0]
dZ = dP[2, 0]

[e, n, u] = ECEF2enu(lats, lons, dX, dY, dZ)

az = arctanc(e, n)
d = sqrt(n**2 + e**2 + u**2)
h = u

print("Retningsvinkel: {:8.5f} gon".format(rad2grad(az)))
print("Skråavstand:    {:8.3f} m".format(d))
print("Høydeforskjell: {:8.3f} m".format(h))

Retningsvinkel: 296.42755 gon
Skråavstand:     120.558 m
Høydeforskjell:    1.427 m
