In [1]:
from numpy import array, sin, cos, set_printoptions
from geodesy import deg2rad

set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

P1 = array([[1],
            [2],
            [1]]) # Homogeneous coordinates

# Translation
T = array([[1, 0, 2],
           [0, 1, 3],
           [0, 0, 1]])

# Scale
S = array([[0.5, 0, 0],
           [0, 2, 0],
           [0, 0, 1]])

# Rotation
alpha = deg2rad(30)
R = array([[cos(alpha), sin(alpha), 0],
           [-sin(alpha), cos(alpha), 0],
           [0, 0, 1]])
print(R)

[[0.866 0.500 0.000]
 [-0.500 0.866 0.000]
 [0.000 0.000 1.000]]


In [2]:
# Translation
P2 = T@P1
print(P2)

[[3]
 [5]
 [1]]


In [3]:
# Scale
P2 = S@P1
print(P2)

[[0.500]
 [4.000]
 [1.000]]


In [4]:
# Rotation
P2 = R@P1
print(P2)

[[1.866]
 [1.232]
 [1.000]]


In [5]:
# Combined transformations
P2 = R@S@(T@P1)
print(P2)

[[6.299]
 [7.910]
 [1.000]]
