In [1]:
from numpy import array, sin, cos
from geodesy import deg2rad

# Translation

P1 = array([[2],
            [1]])

T = array([[3],
           [2]])

P2 = T + P1
print(P2)

[[5]
 [3]]


In [2]:
# Scale

S = array([[1, 0],
           [0, 2]])

P2 = S@P1
print(P2)

[[2]
 [2]]


In [3]:
# Rotation

alpha = deg2rad(30)

R = array([[cos(alpha), -sin(alpha)],
           [sin(alpha), cos(alpha)]])

P2 = R@P1
print(P2)

[[1.23205081]
 [1.8660254 ]]
